166 move background initialization to the main correctbackgroundaccurate pipeline step
SINTEF/pyopia pull request #172
Opened 2024-08-09 14:40 UTC by nepstad

2024-08-09 16:40 UTC, emlynjdavies commented on pyopia/pipeline.py
> +    Obtained from :class:`pyopia.background.CorrectBackgroundAccurater`
CorrectBackgroundAccurater should be CorrectBackgroundAccurate

2024-08-09 17:15 UTC, emlynjdavies requested changes
I get this error in pipline-holo notebook:

```
IndexError                                Traceback (most recent call last)


     plt.style.use('dark_background')
     zval = np.arange(pipeline_steps['initial']['minZ'],
     pipeline_steps['initial']['maxZ'],
     pipeline_steps['initial']['stepZ'])
     plt.hist(zval[xstats.ifocus-1],len(zval))
     plt.xlim(zval[0],zval[-1])
     plt.xlabel('Z [mm]')

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

2024-08-10 06:44 UTC, emlynjdavies commented
> I get this error in pipline-holo notebook:
> 
> ```
> IndexError                                Traceback (most recent call last)
> 
> 
>      plt.style.use('dark_background')
>      zval = np.arange(pipeline_steps['initial']['minZ'],
>      pipeline_steps['initial']['maxZ'],
>      pipeline_steps['initial']['stepZ'])
>      plt.hist(zval[xstats.ifocus-1],len(zval))
>      plt.xlim(zval[0],zval[-1])
>      plt.xlabel('Z [mm]')
> 
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
> ```

NOTE: due to xstats.ifocus not being int

2024-08-11 09:34 UTC, emlynjdavies commented
This seems to work in the holo-pipeline notebook now (have not checked anything else yet).

However, I noticed that the ROIs in the montage are very dark and strange-looking. I think this happened first from version 1.1.3. Is the 255 factor that was added there, causing problems? What are your thoughts, @animmosmith ?

2024-08-11 09:49 UTC, emlynjdavies requested changes
Previously we could run the pipeline on a single image, like this:

MyPipeline = pyopia.pipeline.Pipeline(settings) # this line would create an initial background
stats = MyPipeline.run(filename) # this would process a single image using the background created in the line above

Now, it seems that always the first image we process will be zeroed out. Is there a way to maintain the above functionality?

2024-08-12 14:48 UTC, animmosmith commented
> This seems to work in the holo-pipeline notebook now (have not checked anything else yet).
> 
> However, I noticed that the ROIs in the montage are very dark and strange-looking. I think this happened first from version 1.1.3. Is the 255 factor that was added there, causing problems? (this is a separate issue relating to PR #155) What are your thoughts, @animmosmith ?

Yes - there is an error here - I don't think "rescale_stack" is ever applied but I need to track that through

2024-08-12 14:53 UTC, animmosmith submitted a review, later dismissed

2024-08-12 17:55 UTC, emlynjdavies commented
> > This seems to work in the holo-pipeline notebook now (have not checked anything else yet).
> > However, I noticed that the ROIs in the montage are very dark and strange-looking. I think this happened first from version 1.1.3. Is the 255 factor that was added there, causing problems? (this is a separate issue relating to PR #155) What are your thoughts, @animmosmith ?
> 
> Yes - there is an error here - I don't think "rescale_stack" is ever applied but I need to track that through. I'll raise that as a separate Issue.

Thanks @animmosmith We are working on a fix here: https://github.com/SINTEF/pyopia/pull/174
and I think we need to take a chat about expected output value ranges from the reconstruction

2024-08-12 17:58 UTC, emlynjdavies requested changes
Suggest this will be part of version 1.2 as it introduced breaking changes. Perhaps this, and #91 should be combined first, and then merged to main as version 1.2.0?

2024-08-13 08:23 UTC, emlynjdavies approved these changes

2024-08-13 08:27 UTC, merged

2024-08-15 17:07 UTC, emlynjdavies commented
fixes #164