Holo background test
SINTEF/pyopia pull request #66
Opened 2023-01-11 19:07 UTC by animmosmith

Tests the new background removal (both static and shifting) to work with the holo pipeline. Required modification of some internal variable names within holo.py and also modification of background.py to work with monochrome float64 images as loaded for the hologram processing.

2023-01-11 19:17 UTC, emlynjdavies requested changes
Since the background is corrected in the 'correct background' step in the pipeline, there is no longer need for `imc = pyopia.background.subtract_background(imbg, imraw)` in holo.py

2023-01-12 07:25 UTC, emlynjdavies commented on pyopia/background.py
> +        imc += (255 / 2 - np.percentile(imc, 50))
Just a note, that if not using uint8 images, then the scaling applied here assumes that the value range of pixels in the image could span from 0-255 (i.e. I am not sure what might happen if images were floats with range 0-1)

2023-01-12 07:25 UTC, emlynjdavies approved these changes

2023-01-12 07:34 UTC, animmosmith commented
Yes - I guess this should be a new issue: how to handle varying image types from other instruments

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Emlyn Davies ***@***.***>
Sent: Thursday, January 12, 2023 7:25:36 AM
To: SINTEF/pyopia ***@***.***>
Cc: Alex Nimmo Smith ***@***.***>; Author ***@***.***>
Subject: Re: [SINTEF/pyopia] Holo background test (PR #66)


@emlynjdavies commented on this pull request.

________________________________

In pyopia/background.py<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSINTEF%2Fpyopia%2Fpull%2F66%23discussion_r1067780994&data=05%7C01%7Calex.nimmo.smith%40plymouth.ac.uk%7Ce0f43542c22d4302147108daf46e3389%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C638091051397410357%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EDyKPvs0AYUpKSplichjDo8jScBFe3HI2WfoNGCNsHc%3D&reserved=0>:

>      '''

     imc = np.float64(imraw) - np.float64(imbg)
-    imc[:, :, 0] += (255 / 2 - np.percentile(imc[:, :, 0], 50))
-    imc[:, :, 1] += (255 / 2 - np.percentile(imc[:, :, 1], 50))
-    imc[:, :, 2] += (255 / 2 - np.percentile(imc[:, :, 2], 50))
+    if imc.ndim == 3:
+        imc[:, :, 0] += (255 / 2 - np.percentile(imc[:, :, 0], 50))
+        imc[:, :, 1] += (255 / 2 - np.percentile(imc[:, :, 1], 50))
+        imc[:, :, 2] += (255 / 2 - np.percentile(imc[:, :, 2], 50))
+    else:
+        imc += (255 / 2 - np.percentile(imc, 50))


Just a note, that if not using uint8 images, then the scaling applied here assumes that the value range of pixels in the image could span from 0-255 (i.e. I am not sure what might happen if images were floats with range 0-1)

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSINTEF%2Fpyopia%2Fpull%2F66%23pullrequestreview-1245081102&data=05%7C01%7Calex.nimmo.smith%40plymouth.ac.uk%7Ce0f43542c22d4302147108daf46e3389%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C638091051397410357%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a61Uq2qa%2FZ6EKmC2CPpvF%2BsbHDChZ2H2QC1cgc1%2B23k%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACIA5HX2GMU33YX6FISF3A3WR6WXBANCNFSM6AAAAAATYMJVYU&data=05%7C01%7Calex.nimmo.smith%40plymouth.ac.uk%7Ce0f43542c22d4302147108daf46e3389%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C638091051397410357%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zefOXxxYqAlVANJ%2FIJnVcQBNWsQlPvoBmQuqMwWKTKw%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

2023-01-12 07:38 UTC, merged